language: bash
sudo: required
env:
  global:
    - secure: "JL8IcK5Yy74ny1URG0eR2WkgGZ454pFXVPkZveLUJj621c2BPlY+VG1RqaiAIlfzu7VIlsV8QxIipzBetR7l9OuVGyIVxYQU2A5bUddQAaqSeCYI0GuG0ijDw9ttsM0m14hCzXbRHmREHYFVVr1Er7y7lo99Dv641MtHsPdqakru84g45LdFUPIimDl0GetlI1fRKwRwyeBTfk2EVaiG52PdQdLcO+5wJUmyvWSBNEEYXDE2VODWsQ23wrHofxXH2PyuZ1G43BPGuImnX6iQfyJjpb1Y/XR0jU6w3a9AlxmG0lmSoT5pwnuG7fB6FOcm9NOvNF/+eBaO4Ko6z2IopJeuraeay5uKKQb9/jGXRod3WumNI1H7Q7lVLapqizY3UcdCLE0osDNrD8G6R9gr0FbDiOdHIqwRBZPmtdoY26eJxg0u79FmpgeoKo2VpYBR+BTKLnVGS53n7u8vqKZ/CadcqpDA8oUl/zhbTTC0YxFUfRvhr3CooHBTw7dQaQD4wyXU8FD7oxcEEWVun42wEtR54H4oM3TQrQ7lBEs497+2sJBUdex1XYit8VIRVDJ+gQOtvNAOqXHqDAtKsmk58M7C29JCC7/angrUxj0Jn/m859VE3ylip2mP8CpWsEhkRxNUv7H9BTdC66ofApAfuADvnkMk3mJHwQroIn8vPo4="
    - secure: "VOtYZBPiBDz9ACWc+RHH2x/6VWO4EStMvCual/7G8Kd7NWmp7Gbbl+ZBARet1snvz3rqO70zTcC4xaGh6+QTt4no2BpL5yPbtsXPcrjV2r43v20MOzeVBrBHU175P1YbJJ4z+bbZCTrsAhC3IIPZZIokxy5CH2ig4GVOTycD1F97rpmIUk4WThejWXWDx2QdijW2KPaZ1SJViQwP3Rk6wXr735Y/0mLJpgxR6ner3ev8Sse7XG47vDIJ03DGneZHVZxKnih7qRV0z3QHSmH8qPBLBBjagJPNfEBRJEbne8Zi+Du2bB2AHtH7ZgZcClQMeU3XyweKDgDfz8bOMTw0r/okJqY3/CquGYFfEpaLf8ohUgGfilYrZo209Wtw33b3Ep6xCG+MemZ4Q7dopxi04yJILUukQt8uLmUk0XUh5lNKKtqJVIRu3hcgVfH0pLXHZA+fvEHkw+IWNzK3ccT9PVvFoC9cg1Q0iE9ZdwOBGyiXJhsnKbg9OKmBHG9b9GQkVOtFEjV9i7U5+PFSb+0/WyIDKsy4zXDPAXqD5/tfUeHYuYOWmGBBq2teyhpom+XbkN4weJhxyUMmQrx2GE6RFrE+QhCW6NQOkS27DW/I19C/o5NFrgKpAb840yh5XZ8i2ynGBzaL0yEylnqQbi8TBZqW25fOmIvjqObHFh5vJrc="
    - secure: "UBpp5Q/RiECH84QuvVfypfCwBtWWfjXvmlN4NV/Y86J7sbZd+CDsOCYJgGJAi80pJ5IWfkO8T6Ta/wGagALB0i1GUTAh686EDkdyUqcw8p3Fi7LOm3e9hSDA2CB2q2cssPWi0Xh96f17saDKc33XB7pkzgPZgy2lhTcyuFpRk1cAvq4Q/ZYy8VC8ZYL7OD3P5Ori9vjsZBINGGulpIChSU2Nkggc230aq4pXnMfexVjxnXuxW41ChTUtni4klJ2yoAZEU6UCBdp0dugyqLmppO3Za7OyVakO5nYEG1dKa5cb/YKgR9vLutCnFgtPI5sQyvwV++g2k4gB0zyrh0l/ro+iunjUhCSrK4qvC/JDuVhFlA2Mb6tHn8YQlwcsmK4Srgc37/H9rSomLy9L4NqIEwyHSi9b46Pzeqrp/I2hiEvGj8ZuDCGsWhiyN7R8M9kylUKUt4+0BNEqEnL9pUwvcnFw9dbW89T3G9PkjFKosr9WakKhsRtcVMsWdie6d4MLOefqcjY2Vy79tzlTqm4XhjEvOIT+KTdaxBQtlJY7zzzr+DO3mJbFUvKFqZr0ueOPbNmyFLUBl4MT72J6UwKsHYhmaBdk1E0FuhBwP07ul148LyKZmyymc8GvTTfoMp8qkJsYNa5FgTR0lqy0/9vTZHW8JgRtHyjMdIXRWy9/WmY="
    - K8S_OPS_REPO_BRANCH=master
    - K8S_OPS_REPO_SLUG=hasadna/hasadna-k8s
    - DOCKER_IMAGE=orihoch/odata-ckan
    - DEPLOY_YAML_UPDATE_FILE=values.auto-updated.yaml
    - DEPLOY_VALUES_CHART_NAME=odata
    - DEPLOY_VALUES_IMAGE_PROP=ckanImage
    - DEPLOY_COMMIT_MESSAGE="automatic update of odata-ckan"
    - DEPLOY_GIT_EMAIL=deployer@odata.org.il
    - DEPLOY_GIT_USER=odata_deployer
services:
  - docker
script:
  - curl -s https://raw.githubusercontent.com/hasadna/hasadna-k8s/master/apps_travis_script.sh > ckan/.travis.sh
  - cd ckan && bash .travis.sh script
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
