version: "3.7"

services:

  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  solr:
    build: ./solr
    ports:
      - "8983:8983"
    volumes:
      - "solrdata:/opt/solr/server/solr/ckan/data"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  dbdata:
  solrdata:
