version: '3.2'

services:

  redis:
    image: redis:alpine
    ports:
     - "16379:6379"

  db:
    image: postgres:9.6.3-alpine
    environment:
      - "POSTGRES_PASSWORD=123456"
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "15432:5432"

  solr:
    build: solr
    image: orihoch/data4dappl-solr
    ports:
     - "18983:8983"

  ckan:
    depends_on:
      - redis
      - db
      - solr
    image: orihoch/data4dappl-ckan
    ports:
      - "5000:5000"

volumes:
  db:
