name: data4dappl-pipelines
channels:
  - defaults
dependencies:
  - python>=3.7
  - jupyterlab>=0.35.3
  - pip:
    - dataflows-shell>=0.0.8
    - datapackage>=1.5.1
    - kvfile>=0.0.6
    - requests>=2.20.1
    - sqlalchemy>=1.2.14
    - tableschema>=1.2.5
    - tableschema-sql>=0.10.4
    - tabulate>=0.8.2
    - tabulator>=1.19.0
    - unicodecsv>=0.14.1
    - unidecode>=0.4.21
