#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: ckan-initialize-db
#spec:
#  template:
#    metadata:
#      name: ckan-initialize-db
#    spec:
#      containers:
#      - name: ckan-initialize-db
#        image: orihoch/data4dappl-ckan
#        args: ["db", "init", "-c", "/etc/ckan/default/development.ini"]
#        resources:
#          requests:
#            cpu: 1m
#        volumeMounts:
#        - name: etc-ckan-default
#          mountPath: /etc/ckan/default
#          readOnly: true
#      volumes:
#      - name: etc-ckan-default
#        secret:
#          secretName: etc-ckan-default
#      restartPolicy: Never
