#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: ckan-restore-data
#spec:
#  template:
#    metadata:
#      name: ckan-restore-data
#    spec:
#      nodeSelector:
#        # loads data dump from hostPath
#        # TODO: change to use network shared filesystem
#        kubernetes.io/hostname: gke-data4dappl-default-pool-29af7936-z7tf
#      containers:
#      - name: ckan-restore-data
#        # this image was updated with psql which is needed to restore db
#        image: gcr.io/hasadna-odata/data4dappl-ckan:34085ec7df43172d33c7fb53858374af76886be1
#        command:
#        - "bash"
#        - "-c"
#        - >
#          tar -xzvf /var/ckan-dump/data.tar.gz -C /var/lib/ckan
#        resources:
#          requests:
#            cpu: 5m
#        volumeMounts:
#        - name: etc-ckan-default
#          mountPath: /etc/ckan/default
#          readOnly: true
#        - name: ckan-dump
#          mountPath: /var/ckan-dump
#        - name: ckan-data
#          mountPath: /var/lib/ckan
#      volumes:
#      - name: etc-ckan-default
#        secret:
#          secretName: etc-ckan-default
#      - name: ckan-dump
#        hostPath: {path: /var/ckan-dump}
#      - name: ckan-data
#        persistentVolumeClaim:
#          claimName: ckan-data
#      restartPolicy: Never
