apiVersion: v1
kind: Service
metadata: {name: ckan}
spec:
  ports:
  - {name: '5000', port: 5000}
  selector: {app: ckan}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: ckan-data}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: {storage: 20Gi}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: ckan}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: ckan}
    spec:
      containers:
      - image: gcr.io/hasadna-odata/data4dappl-ckan:68f204eb8d4ae18ed7d2c9bcd1d755dd583d5f20
        name: ckan
        ports:
        - {containerPort: 5000}
        resources:
          requests: {cpu: 50m}
        volumeMounts:
        - {mountPath: /var/lib/ckan, name: ckan-data, subPath: ckan}
        - {mountPath: /etc/ckan/default, name: etc-ckan-default, readOnly: true}
      volumes:
      - name: etc-ckan-default
        secret: {secretName: etc-ckan-default}
      - name: ckan-data
        persistentVolumeClaim: {claimName: ckan-data}
