apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
  - name: "5432"
    port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - env:
        - {name: POSTGRES_PASSWORD, valueFrom: {secretKeyRef: {name: "env-vars", key: "POSTGRES_PASSWORD"}}}
        image: postgres:9.6.3-alpine
        name: db
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 20m
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
          # postgresql doesn't like being on root of device
          subPath: data
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db
